from pathlib import Path
from html import escape
entries=[
('prepare-lookup','1. Prepare the lookup','Run once after each upload. Reads the lowercase headers from latest.csv or high_confidence.csv, refangs values, keeps supported types, and replaces swiftioc_iocs.csv. Do not use the investigation workspace CSV, which has different headers. Requires permission to write lookup files.'),
('verify-lookup','2. Verify coverage','Check the counts before hunting. Preparation age is not upstream observation freshness; inspect sf_last_seen on findings and the collection diagnostics. Zero rows, missing expected types, or lookup errors need investigation.'),
('network-ips','3. Hunt source and destination IPs','Map src_ip and dest_ip to your network fields. Both endpoints are checked independently, so a source hit does not hide a destination hit. Exact IP matching only: CIDR ranges are excluded. IPv6 spelling must match the feed’s normalized representation; compressed/expanded variants are not automatically equivalent.'),
('dns-domains','4. Hunt exact DNS domains','Map query to the DNS question name, not a URL. Lowercases names and removes the final DNS dot. This matches exact domains only: a hit on example.test does not imply a hit on child.example.test. Counts are matching log events, not unique compromises.'),
('sha256-files','5. Hunt SHA-256 file hashes','Map sha256 to a dedicated SHA-256 field. Composite hash strings such as “SHA256=…” must be extracted first. Do not map an MD5 or SHA-1 field into sha256.'),
('exact-urls','6. Hunt exact URLs','Map url to the complete URL including scheme, path, and query string. Refangs hxxp/hxxps and [.] without lowercasing the path or query. This intentionally uses exact matching: host case, percent encoding, default ports, and query ordering differences may miss. Do not enable case-insensitive lookup matching globally.'),
]
html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Splunk IOC hunts · SwiftIOC</title><link rel="stylesheet" href="guide.css?v=1"><script defer src="guide.js?v=1"></script></head><body><main>
<a href="../">← SwiftIOC dashboard</a><p class="eyebrow">ANALYST PLAYBOOK / SPLUNK</p><h1>From IOC feed to matching events.</h1><p>Upload one lookup, choose a hunt, and map your event fields. These SPL templates use lookup enrichment instead of building a large IOC subsearch. They do not require Splunk Enterprise Security or accelerated data models.</p>
<nav aria-label="SPL sections">'''
html+=''.join(f'<a href="#{key}">{escape(title)}</a>' for key,title,_ in entries)
html+='''</nav><section><h2>Before your first hunt</h2><ol><li>Download <a href="../iocs/latest.csv" download>the full retained CSV</a> or <a href="../iocs/high_confidence.csv" download>the high-confidence subset</a>. The subset can miss indicators excluded by its policy.</li><li>In Splunk: <strong>Settings → Lookups → Lookup table files → Add new</strong>. Upload it as <code>swiftioc_raw.csv</code> in the app where you will run these searches. Configure permissions so intended analysts can read both lookup files.</li><li>Run “Prepare the lookup,” then “Verify coverage.” Re-upload a fresh CSV and rerun preparation for each snapshot. A valid empty snapshot should remove old matches; verify your input before replacing the working lookup.</li><li>Replace <code>YOUR_*_INDEX</code> with a specific index and map the event fields listed on the hunt. Use extracted, single-valued fields. Start with the last 24 hours and inspect results before broadening the time range.</li></ol><p>The URL hunt requires the default case-sensitive CSV lookup behavior. Existing lookup definitions with different matching settings are not supported by these exact-match templates. Unsupported types, including CVEs and CIDRs, are deliberately excluded during preparation.</p></section><p id="copy-status" role="status" aria-live="polite"></p>'''
for key,title,description in entries:
 code=Path(f'public/splunk/{key}.spl').read_text(encoding="utf-8")
 html+=f'<section id="{key}"><h2>{escape(title)}</h2><p>{escape(description)}</p><div class="actions"><button type="button" data-copy="code-{key}">Copy SPL</button><a href="{key}.spl" download>Download .spl</a></div><pre><code id="code-{key}">{escape(code)}</code></pre></section>'
html+='''<section><h2>Validate before scheduling</h2><p>These templates have not been executed against your Splunk deployment. First verify the lookup with a known indicator and a matching test event in your own environment. No results can mean missing telemetry, incorrect field mapping, naming differences, or limited feed coverage.</p><p>Use narrow indexes and time windows. For recurring hunts, save the search in the same app as its lookups and set an appropriate schedule. Delivery delays may require overlapping windows and alert deduplication. Retained-feed matches are investigation leads, not proof of compromise or an automatic blocking verdict.</p><p>Need CIDR or subdomain matching? Use separately reviewed lookup definitions; do not turn on wildcard matching for the combined URL/hash table.</p><p>Official reference: <a href="https://help.splunk.com/en/splunk-enterprise/spl-search-reference/10.0/search-commands/lookup">lookup</a> · <a href="https://help.splunk.com/en/splunk-enterprise/spl-search-reference/9.2/search-commands/inputlookup">inputlookup</a>.</p></section></main></body></html>'''
Path('public/splunk/index.html').write_text(html+'\n', encoding="utf-8")
